### ISSUE TITLE
Jumps to the top

### ISSUE THREAD

**Issue by mihai-vlc** [zertosh/jquery-audit#5]
When i have this extension enabled on the elements tab keeps jumping to the top if there are any changes in the dom caused by js.

You can test it here: http://flexslider.woothemes.com/

**Comment by zertosh** [comment]
Thanks for pointing it out.

I just pushed a fix to the Chrome Web Store. The issue was with the helper comment nodes for `document` and `window`. Turns out that when they're in a node that's an ancestor of `<html>`, that jumping happens.

I moved the helper nodes to be the first children of `<html>` instead, and also added a options page so you can turn them off.
